### ISSUE TITLE
feature requirements should fail the feature if the step fails, not skip

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/reconciler-test#181] opened 2021-04-20 18:14 UTC
example:

``` 
   channel_test.go:51: Skipping feature 'Knative Channel Specification - Data Plane/Delivery Spec 0' assertions because requirement "wait until done" failed
```

results in a skipped step and a `PASS`, but the test did not run or pass. These should `FAIL`.

**Comment by lionelvillard** [comment] 2021-04-20 18:24
maybe a duplicate of https://github.com/knative-sandbox/reconciler-test/issues/166?

**Closed** 2021-04-20 20:18 UTC
